// formx/frontend/src/pages/Login.tsx
import { useState } from 'react';
import type { FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { api, readLoginNotice } from '../lib/api';

export function Login() {
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [rememberMe, setRememberMe] = useState(true);
  const [error, setError] = useState(readLoginNotice);
  const [loading, setLoading] = useState(false);

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      await api.auth.login({ email, password }, { rememberMe });
      document.body.style.removeProperty('overflow');
      document.body.style.removeProperty('padding-right');
      navigate('/', { replace: true });
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Login failed');
    } finally {
      setLoading(false);
    }
  }

  const fieldClass =
    'w-full rounded-lg border border-cyan-400/35 bg-[#1e3044] px-3 py-2 text-sm text-slate-100 shadow-xs outline-none transition placeholder:text-slate-400/80 focus:border-sky-400 focus:ring-2 focus:ring-sky-400/25';

  return (
    <div
      className="min-h-dvh flex items-center justify-center p-4 text-slate-100"
      style={{
        colorScheme: 'dark',
        background:
          'radial-gradient(circle at 18% 14%, rgba(56, 189, 248, 0.14), transparent 45%), radial-gradient(circle at 85% 88%, rgba(37, 99, 235, 0.12), transparent 48%), linear-gradient(165deg, #1a2636 0%, #1f354a 52%, #1a2839 100%)',
      }}
    >
      <div className="w-full max-w-sm rounded-2xl border border-cyan-400/35 bg-[#1c2a3c]/95 p-8 shadow-[0_16px_42px_rgba(8,14,24,0.42)] backdrop-blur-sm">
        <div className="mb-6 flex items-center gap-2">
          <span className="text-2xl">📄</span>
          <div>
            <h1 className="text-lg font-semibold text-[#eaf4fb]">TranForm</h1>
            <p className="text-xs text-[#93adc4]">Sign in with your Morph account. Opening Event Logs from MorphUtils after that skips this form.</p>
          </div>
        </div>
        <form onSubmit={onSubmit} className="grid gap-4">
          <div className="grid gap-1.5">
            <label htmlFor="login-email" className="text-xs font-medium text-[#b8cfe0]">
              Email
            </label>
            <input
              id="login-email"
              type="email"
              autoComplete="email"
              placeholder="you@example.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              className={fieldClass}
            />
          </div>
          <div className="grid gap-1.5">
            <label htmlFor="login-password" className="text-xs font-medium text-[#b8cfe0]">
              Password
            </label>
            <input
              id="login-password"
              type="password"
              autoComplete="current-password"
              placeholder="••••••••"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              className={fieldClass}
            />
          </div>
          <label className="flex cursor-pointer items-center gap-2 text-sm text-[#b8cfe0]">
            <input type="checkbox" checked={rememberMe} onChange={(e) => setRememberMe(e.target.checked)} />
            Remember me on this device
          </label>
          {error ? (
            <div className="rounded-lg border border-red-400/45 bg-red-950/35 px-3 py-2 text-sm text-red-100">{error}</div>
          ) : null}
          <button
            type="submit"
            disabled={loading}
            className="mt-1 w-full rounded-lg bg-sky-600 px-4 py-2.5 text-sm font-medium text-white shadow-sm transition hover:bg-sky-700 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {loading ? 'Signing in…' : 'Sign in'}
          </button>
        </form>
      </div>
    </div>
  );
}

// SharpReport/frontend/src/routes/(auth)/login/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { auth, login } from '$lib/stores/auth.svelte';
	import { goto } from '$app/navigation';

	let email = '';
	let password = '';
	let rememberMe = true;
	let error = '';
	let loading = false;

	async function handleLogin() {
		if (!email || !password) {
			error = 'Please enter email and password';
			return;
		}

		loading = true;
		error = '';

		try {
			await login(email, password, { rememberMe });
			goto('/');
		} catch (err) {
			error = err instanceof Error ? err.message : 'Login failed';
		} finally {
			loading = false;
		}
	}

	onMount(() => {
		if ($auth.isAuthenticated) {
			goto('/');
		}
	});
</script>

<div class="auth-panel space-y-6 p-8">
	<div class="text-center">
		<h1 class="text-2xl font-bold">DataX</h1>
		<p class="text-text-secondary mt-2">Sign in with your platform account</p>
	</div>

	{#if error}
		<div class="p-3 bg-error/10 text-error rounded text-sm">
			{error}
		</div>
	{/if}

	<form on:submit|preventDefault={handleLogin} class="space-y-4">
		<div>
			<label for="email" class="block text-sm font-medium mb-1">Email</label>
			<input
				id="email"
				type="email"
				bind:value={email}
				required
				class="w-full px-3 py-2 bg-bg-secondary border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-accent-primary"
			/>
		</div>

		<div>
			<label for="password" class="block text-sm font-medium mb-1">Password</label>
			<input
				id="password"
				type="password"
				bind:value={password}
				required
				class="w-full px-3 py-2 bg-bg-secondary border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-accent-primary"
			/>
		</div>

		<label class="flex items-center gap-2 text-sm text-text-secondary">
			<input type="checkbox" bind:checked={rememberMe} class="rounded border-border" />
			Remember me on this device
		</label>

		<button
			type="submit"
			disabled={loading}
			class="w-full py-2 px-4 bg-accent-primary text-white rounded-md hover:bg-opacity-90 transition-colors disabled:opacity-50"
		>
			{#if loading}
				Signing In...
			{:else}
				Sign In
			{/if}
		</button>
	</form>

	<div class="text-center text-sm text-text-secondary">
		<p>
			First-time DataX setup?
			<a href="/setup" class="text-accent-primary hover:underline">Configure Metabase</a>
		</p>
	</div>
</div>
